version: '2'

services:
  mongo:
    image: mongo:3.2.15
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - /tmp/data/db:/data/db

  web-app:
    image: pos
    container_name: pos-forked
    ports:
      - "3000:3000"
    environment:
      - username=923028669877
      - password=8316
      - secret=posSecret
      - mongourl=mongodb://mongo:27017/pos
    depends_on:
      - mongo
    